[package]
name = "texpresso"
version.workspace = true
description = "TeXPresso：本地运行的 TeX 完整 IDE（实时编译）"
authors = ["TeXPresso"]
edition.workspace = true

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "texpresso_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "devtools"] }
tauri-plugin-opener = "2"
tauri-plugin-log = "2"
tauri-plugin-window-state = "2"
tauri-specta = { version = "=2.0.0-rc.25", features = ["derive", "typescript"] }
specta-typescript = "0.0.12"
specta = { version = "=2.0.0-rc.25", features = ["derive"] }
texpresso-core = { path = "../crates/texpresso-core" }
serde.workspace = true
serde_json = "1"
tokio.workspace = true
tokio-util.workspace = true
notify = "8.2"
async-trait.workspace = true
thiserror.workspace = true
tracing = "0.1"
tracing-subscriber = "0.3"
tauri-plugin-dialog = "2.7.2"
tauri-plugin-mcp-bridge = "0.12"
